### ISSUE TITLE
OPENROUTER_KEY is not passed through to the OpenAI client, resulting in 401 error

### ISSUE THREAD

**Issue by cmungall** [simonw/llm-openrouter#7]
The docs state that either "You can set that as an environment variable called OPENROUTER_KEY, or add it to the llm set of saved keys"
https://github.com/simonw/llm-openrouter?tab=readme-ov-file#configuration

However, if the env var path is chosen and `llm keys set openrouter` is not used this results in

```
Error: Error code: 401 - {'error': {'message': 'Missing Authentication header or invalid API key', 'code': 401}}
```

On debugging it seems that the OPENAI_KEY env var takes priority.

Either the docs should state that the `keys` command must be used, or the env var should be passed through.

**Comment by tosh** [comment]
I just also ran into this. Worked around it by explicitly passing the API key.
